url=http://es.local:9200
insecureSkipVerify=true
index=e2e-source-index
settings=test/e2e/enrich/fixtures/index1-settings.json
mappings=test/e2e/enrich/fixtures/index1-mappings.json
data=test/e2e/enrich/fixtures/index1-data.json
delete=true
add=true
